### ISSUE TITLE
Brain Concurrency

### ISSUE THREAD

**Issue by mrbdahlem** [mrbdahlem/ZombieLand#1]
Concurrency issues with brain objects.
takeBrain() needs to be synchronized with ZombieLand goal checking
takeBrain() needs to be synchronized with Brain.act(), brain may be removed while image is being updated

This possibly also exists in Fire, Bucket, etc... fire/bucket may be removed from world while goal checking is occurring.

**Comment by mrbdahlem** [comment]
Exception in thread "Thread-23" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at greenfoot.collision.ColManager.makeCollisionObjects(ColManager.java:66)
	at greenfoot.collision.ColManager.getObjectsAt(ColManager.java:163)
	at greenfoot.World.getObjectsAt(World.java:574)
	at greenfoot.Actor.getObjectsAtOffset(Actor.java:896)
	**at Zombie.isTouching(Zombie.java:191)
	at Zombie.isBrainHere(Zombie.java:277)
	at MyZombie.plan(MyZombie.java:28)**
	at Zombie$1.run(Zombie.java:53)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrbdahlem** [comment]
Brains appears to be solved, fire can lead to Actor not in world exceptions upon zombie collision.
